#!/bin/bash
#
# Amazon update script

TMPDIRNAME=letterboxd-amazon

. $(dirname $0)/../libexec/tool-base.sh

JAVA_OPTS="-Xmx4096M"
#JAVA_OPTS="$JAVA_OPTS -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode"
JAVA_OPTS="$JAVA_OPTS -Djava.io.tmpdir="$TMPDIR" -cp $CP"
if [ $DEV == 0 ]; then
	JAVA_OPTS="$JAVA_OPTS -Dletterboxd.live=true"
fi
#JAVA_OPTS="$JAVA_OPTS -Dletterboxd.useCachedNetflixData=true"
#JAVA_OPTS="$JAVA_OPTS -Dletterboxd.useExistingSearchIndex=true"

if [ $CONTINUE == 1 ]; then
	JAVA_OPTS="$JAVA_OPTS -Damazon.update.continue=true"
fi

java $JAVA_OPTS com.letterboxd.tools.amazon.AmazonUpdate $* 2>&1 | tee "$TMPDIR"/update.log
