#!/bin/bash
#
# Film image resizing tool script

. $(dirname $0)/../libexec/tool-base.sh

JAVA_OPTS="-Xmx4096M"
#JAVA_OPTS="$JAVA_OPTS -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode"
JAVA_OPTS="$JAVA_OPTS -Djava.io.tmpdir=/srv/tomcat/letterboxd/temp -cp $CP"
if [ $DEV == 0 ]; then
	JAVA_OPTS="$JAVA_OPTS -Dletterboxd.live=true"
fi
#JAVA_OPTS="$JAVA_OPTS -Dletterboxd.useCachedNetflixData=true"
#JAVA_OPTS="$JAVA_OPTS -Dletterboxd.useExistingSearchIndex=true"

java $JAVA_OPTS com.letterboxd.tools.FilmImageResizingTool $*
