#!/bin/bash
#
# iTunes update script

if [ $(id -un) != "availability" ]; then
	echo "This script must be run as availability user"
	exit 1
fi

TMPDIRNAME=itunes
. $(dirname $0)/../libexec/tool-base-options.sh
. $(dirname $0)/../libexec/tool-base.sh

JAVA_OPTS="-Xmx4096M"
#JAVA_OPTS="$JAVA_OPTS -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode"
JAVA_OPTS="$JAVA_OPTS -Djava.io.tmpdir="$TMPDIR" -cp $CP"
if [ $DEV == 0 ]; then
	JAVA_OPTS="$JAVA_OPTS -Dletterboxd.live=true"
fi
#JAVA_OPTS="$JAVA_OPTS -Dletterboxd.useCachedNetflixData=true"
#JAVA_OPTS="$JAVA_OPTS -Dletterboxd.useExistingSearchIndex=true"

java $JAVA_OPTS com.letterboxd.tools.itunes.ITunesUpdate "$TMPDIR"/index "$TMPDIR"/extract "$TMPDIR"/extract 2>&1 | tee "$TMPDIR"/update.log
