#!/bin/bash
#
# iTunes Download and Update wrapper

if [ $(id -un) != "availability" ]; then
	echo "This script must be run as availability user"
	exit 1
fi

TMPDIRNAME=itunes
. $(dirname $0)/../libexec/tool-base.sh

BASE_DIR=$(dirname $0)

SKIP_DOWNLOAD=0

while getopts ":d" opt; do
  case $opt in
    d)
      SKIP_DOWNLOAD=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $((OPTIND-1))

if [ $SKIP_DOWNLOAD == 0 ]; then
	# Download
	$BASE_DIR/itunes-download

	if [ $? != 0 ]; then
		echo "*** iTunes download failed"
		exit 1
	fi
fi

# Update
$BASE_DIR/itunes-update
if [ $? != 0 ]; then
	echo "*** iTunes update failed"
	exit 1
fi
