#!/bin/bash
#
# Netflix update script

if [ $(id -un) != "letterboxd" ]; then
	echo "This script must be run as letterboxd"
	exit 1
fi

TOOLSJAR=/srv/tools/letterboxd-tools-1.0-SNAPSHOT-jar-with-dependencies.jar

TMPDIR=/tmp/netflix-update
mkdir -p "$TMPDIR"

CP=$TOOLSJAR:`ls /opt/tomcat/lib/*.jar | xargs echo | sed -e 's/ /:/g'`

JAVA_OPTS="-Xmx2048M"
#JAVA_OPTS="$JAVA_OPTS -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode"
JAVA_OPTS="$JAVA_OPTS -Djava.io.tmpdir="$TMPDIR" -cp "$WEBINFDIR"/classes:$CP"
JAVA_OPTS="$JAVA_OPTS -Dletterboxd.live=true"
#JAVA_OPTS="$JAVA_OPTS -Dletterboxd.useCachedNetflixData=true"
#JAVA_OPTS="$JAVA_OPTS -Dletterboxd.useExistingSearchIndex=true"

java $* $JAVA_OPTS com.letterboxd.tools.netflix.NetflixUpdate 2>&1 | tee "$TMPDIR"/update.log
